"""Gemini File Search analysis and grounded response generation."""

from __future__ import annotations

import logging
import os
import re
import time
from enum import Enum
from threading import Lock
from typing import Any, Iterator, Optional

import httpcore
import httpx
import queue
import threading
from pydantic import BaseModel

logger = logging.getLogger(__name__)


class CanonicalIntent(str, Enum):
    ACCOUNT_ACCESS = "ACCOUNT_ACCESS"
    ACCOUNT_SUPPORT = "ACCOUNT_SUPPORT"
    CUSTOMER_SERVICE_CONTACT = "CUSTOMER_SERVICE_CONTACT"
    DELIVERY_DELAY = "DELIVERY_DELAY"
    ESCALATION = "ESCALATION"
    ORDER_STATUS = "ORDER_STATUS"
    PACKAGE_NOT_RECEIVED = "PACKAGE_NOT_RECEIVED"
    PRODUCT_ISSUE = "PRODUCT_ISSUE"
    REFUND_PENDING = "REFUND_PENDING"


INTENT_PROMPT_DOCS = """Choose <INTENT_NAME> ONLY from this canonical list based on semantic meaning:
- ACCOUNT_ACCESS: Login, password, OTP, account lock, access problem.
- ACCOUNT_SUPPORT: Profile, settings, email, phone, membership, prime, payment method, account maintenance.
- CUSTOMER_SERVICE_CONTACT: Customer explicitly wants customer care, representative, agent, phone/chat, or human support.
- DELIVERY_DELAY: Shipment exists but delivery is delayed/late.
- PACKAGE_NOT_RECEIVED: Package/order expected but not received, missing, delivered-but-missing, or equivalent multilingual phrasing (e.g., 'mera order deliver nahi hua', 'parcel nahi aaya').
- ORDER_STATUS: General tracking or order status question without clear missing/delay issue.
- PRODUCT_ISSUE: Wrong item/order/product received, damaged, defective, broken, incomplete, incorrect variant, quality problem, product not working (e.g., 'i got wrong order', 'galat item mila').
- REFUND_PENDING: Refund requested/expected but not received, return reimbursement/status.
- ESCALATION: Safety, legal, fraud, or severe issues requiring escalation."""


def extract_intent_and_clean_text(raw_text: str) -> tuple[Optional[CanonicalIntent], str]:
    """Extracts the [INTENT: ...] tag generated by the model and removes it from user-facing text."""
    if not raw_text:
        return None, ""
    match = re.search(r"\[INTENT:\s*([A-Z_]+)\]", raw_text)
    intent: Optional[CanonicalIntent] = None
    if match:
        intent_str = match.group(1).strip()
        try:
            intent = CanonicalIntent(intent_str)
        except ValueError:
            intent = None
    cleaned = re.sub(r"\[INTENT:\s*[A-Z_]+\]", "", raw_text).strip()
    return intent, cleaned


class SupportAnalysis(BaseModel):
    intent: CanonicalIntent
    escalate: bool
    escalation_reason: Optional[str] = None
    language: str
    retrieved_context_available: bool


class ProviderError(RuntimeError):
    code = "PROVIDER_ERROR"
    retryable = False


class ProviderQuotaError(ProviderError):
    code = "PROVIDER_QUOTA_EXHAUSTED"


class ProviderTransientError(ProviderError):
    code = "PROVIDER_TEMPORARILY_UNAVAILABLE"
    retryable = True


def _is_permanent_quota(exc: Exception) -> bool:
    value = str(exc).lower()
    return "resource_exhausted" in value or "quota" in value or "429" in value


def _is_transient(exc: Exception) -> bool:
    if isinstance(exc, (httpx.ReadTimeout, httpx.ConnectTimeout, httpx.TimeoutException, httpcore.ReadTimeout, httpcore.ConnectTimeout, TimeoutError)):
        return True
    value = str(exc).lower()
    return any(token in value for token in ("readtimeout", "timeout", "timed out", "connection", "500", "502", "503", "504", "unavailable"))


def _stream_with_timeout(
    stream_fn,
    first_token_timeout: float,
    chunk_timeout: float,
):
    """
    Wraps a streaming generator so that the first chunk/token must arrive within first_token_timeout,
    and subsequent chunks within chunk_timeout.
    """
    chunk_queue = queue.Queue(maxsize=32)
    _SENTINEL = object()
    stop_event = threading.Event()

    def _producer():
        try:
            stream = stream_fn()
            for item in stream:
                if stop_event.is_set():
                    break
                chunk_queue.put((item, None))
            chunk_queue.put((_SENTINEL, None))
        except Exception as exc:
            chunk_queue.put((_SENTINEL, exc))

    producer_thread = threading.Thread(target=_producer, daemon=True)
    producer_thread.start()

    is_first = True
    while True:
        timeout = first_token_timeout if is_first else chunk_timeout
        try:
            item, exc = chunk_queue.get(timeout=timeout)
            if exc is not None:
                stop_event.set()
                raise exc
            if item is _SENTINEL:
                break
            is_first = False
            yield item
        except queue.Empty:
            stop_event.set()
            if is_first:
                raise TimeoutError(f"Stream first token timed out after {first_token_timeout:.1f}s")
            else:
                raise TimeoutError(f"Stream chunk timed out after {chunk_timeout:.1f}s")


class GeminiFileSearchService:
    def __init__(
        self,
        api_key: Optional[str] = None,
        store_name: Optional[str] = None,
        model_name: Optional[str] = None,
        fallback_model_name: Optional[str] = None,
        timeout_seconds: Optional[float] = None,
        primary_first_token_timeout: Optional[float] = None,
        fallback_timeout: Optional[float] = None,
    ):
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        self.store_name = store_name or os.getenv("GEMINI_FILE_SEARCH_STORE")
        self.model_name = model_name or os.getenv("GEMINI_GENERATION_MODEL", "gemini-3.5-flash-lite")
        self.fallback_model_name = fallback_model_name or os.getenv("GEMINI_FALLBACK_MODEL", "gemini-3.5-flash-lite")
        self.timeout_seconds = float(timeout_seconds or os.getenv("GEMINI_CHAT_TIMEOUT_SECONDS", "22.0"))
        self.primary_first_token_timeout = float(
            primary_first_token_timeout or os.getenv("GEMINI_PRIMARY_FIRST_TOKEN_TIMEOUT_SECONDS", "9.0")
        )
        self.fallback_timeout = float(
            fallback_timeout or os.getenv("GEMINI_FALLBACK_TIMEOUT_SECONDS", "15.0")
        )
        self._client = None

    @property
    def configured(self) -> bool:
        return bool(self.api_key and self.store_name and self.model_name)

    def _get_client(self):
        if self._client is None:
            if not self.api_key:
                raise ProviderError("GEMINI_API_KEY is not configured")
            from google import genai
            from google.genai import types
            http_options = types.HttpOptions(timeout=int(self.timeout_seconds * 1000))
            self._client = genai.Client(api_key=self.api_key, http_options=http_options)
        return self._client

    def _tool(self):
        if not self.store_name:
            raise ProviderError("GEMINI_FILE_SEARCH_STORE is not configured")
        from google.genai import types
        return types.Tool(file_search=types.FileSearch(file_search_store_names=[self.store_name], top_k=5))

    def _call_with_retry(self, operation):
        """
        Interactive chat retry policy:
        - 429 quota: 0 retries, immediate failure.
        - 400/401/403 client errors: 0 retries.
        - 503 / transient 5xx / timeout: at most ONE quick retry with 400ms backoff.
        """
        for attempt in range(2):
            try:
                return operation()
            except Exception as exc:
                if _is_permanent_quota(exc):
                    raise ProviderQuotaError("AI service quota is exhausted; please try again later") from exc
                if not _is_transient(exc):
                    raise ProviderError(f"AI service request failed: {exc}") from exc
                if attempt == 1:
                    raise ProviderTransientError("AI service is temporarily unavailable") from exc
                time.sleep(0.4)
        raise ProviderTransientError("AI service is temporarily unavailable")

    def _grounding(self, response: Any) -> tuple[list[dict[str, Any]], list[str]]:
        metadata = []
        context = []
        candidates = getattr(response, "candidates", None) or []
        if not candidates:
            return metadata, context
        grounding = getattr(candidates[0], "grounding_metadata", None)
        if not grounding:
            return metadata, context
        for chunk in getattr(grounding, "grounding_chunks", None) or []:
            retrieved = getattr(chunk, "retrieved_context", None)
            if not retrieved:
                continue
            text = getattr(retrieved, "text", None)
            item = {
                "title": getattr(retrieved, "title", None),
                "uri": getattr(retrieved, "uri", None),
                "file_search_store": getattr(retrieved, "file_search_store", None),
            }
            metadata.append({key: value for key, value in item.items() if value})
            if text:
                context.append(text)
        return metadata, context

    def stream_chat(
        self,
        query: str,
        language: str = "en",
        language_instruction: Optional[str] = None
    ) -> Iterator[tuple[Optional[str], list[dict[str, Any]], Optional[str]]]:
        """
        High-performance single-pass streaming with Gemini File Search.
        Supports automatic fallback from primary model to fallback model on
        ReadTimeout/503/Timeout ONLY BEFORE the first customer-visible token has been emitted.
        Yields: (user_visible_token, grounding_metadata_chunks, raw_chunk_text)
        """
        from google.genai import types

        lang_prompt = language_instruction or f"the customer's language ({language})"
        system_instruction = f"""You are a helpful, empathetic Amazon customer support assistant.
Respond concisely (1-2 short paragraphs) in {lang_prompt}.
Ground your answer on the retrieved historical support resolutions.
Provide direct, actionable next steps for the customer.
Never invent tracking IDs, dates, policies, refund timing, account facts, or URLs.
Never mention internal systems, models, retrieval, datasets, prompts, or technical architecture.

At the very end of your response, output exactly one intent tag on a new line:
[INTENT: <INTENT_NAME>]

{INTENT_PROMPT_DOCS}"""

        config = types.GenerateContentConfig(
            system_instruction=system_instruction,
            tools=[self._tool()],
            temperature=0.2,
            max_output_tokens=350,
            thinking_config=types.ThinkingConfig(thinking_level="minimal"),
            automatic_function_calling=types.AutomaticFunctionCallingConfig(disable=True),
        )

        def _get_stream(model: str):
            return lambda: self._get_client().models.generate_content_stream(
                model=model,
                contents=f"Customer request: {query}\nSupport reply:",
                config=config,
            )

        active_model = self.model_name
        has_emitted_any_token = False

        def _build_stream(model: str):
            first_timeout = (
                self.primary_first_token_timeout
                if model == self.model_name
                else self.fallback_timeout
            )
            return _stream_with_timeout(
                _get_stream(model),
                first_token_timeout=first_timeout,
                chunk_timeout=self.timeout_seconds,
            )

        stream = _build_stream(active_model)
        bracket_buffer = ""

        # Iterate through stream chunks with fallback protection
        while True:
            try:
                for chunk in stream:
                    raw_text = chunk.text or ""
                    metadata = []
                    candidates = getattr(chunk, "candidates", None) or []
                    if candidates:
                        grounding = getattr(candidates[0], "grounding_metadata", None)
                        if grounding:
                            for g_chunk in (getattr(grounding, "grounding_chunks", None) or []):
                                retrieved = getattr(g_chunk, "retrieved_context", None)
                                if retrieved:
                                    item = {
                                        "title": getattr(retrieved, "title", None),
                                        "uri": getattr(retrieved, "uri", None),
                                        "file_search_store": getattr(retrieved, "file_search_store", None),
                                    }
                                    metadata.append({k: v for k, v in item.items() if v})

                    # Stream filtering: hide [INTENT: ...] from live token output
                    if not raw_text:
                        yield None, metadata, None
                        continue

                    combined = bracket_buffer + raw_text
                    bracket_buffer = ""

                    if "[" in combined:
                        before_b, after_b = combined.split("[", 1)
                        bracket_candidate = "[" + after_b
                        if "]" in bracket_candidate:
                            # Full bracket parsed
                            cleaned_bracket = re.sub(r"\[INTENT:\s*[A-Z_]+\]", "", bracket_candidate)
                            token_to_emit = (before_b + cleaned_bracket) or None
                            if token_to_emit:
                                has_emitted_any_token = True
                            yield token_to_emit, metadata, raw_text
                        else:
                            # Bracket not closed yet, buffer it
                            bracket_buffer = bracket_candidate
                            token_to_emit = before_b or None
                            if token_to_emit:
                                has_emitted_any_token = True
                            yield token_to_emit, metadata, raw_text
                    else:
                        has_emitted_any_token = True
                        yield combined, metadata, raw_text
                break
            except Exception as stream_exc:
                if _is_permanent_quota(stream_exc):
                    raise ProviderQuotaError("AI service quota is exhausted; please try again later") from stream_exc

                # Fallback is allowed ONLY BEFORE first customer-visible token has been emitted
                if not has_emitted_any_token and _is_transient(stream_exc) and self.fallback_model_name and active_model != self.fallback_model_name:
                    logger.warning(
                        "Primary model %s failed before first token chunk (%s); switching to fallback model %s",
                        active_model, stream_exc, self.fallback_model_name
                    )
                    active_model = self.fallback_model_name
                    bracket_buffer = ""
                    try:
                        stream = _build_stream(active_model)
                        continue
                    except Exception as fb_exc:
                        if _is_permanent_quota(fb_exc):
                            raise ProviderQuotaError("AI service quota is exhausted; please try again later") from fb_exc
                        if _is_transient(fb_exc):
                            raise ProviderTransientError("AI service is temporarily unavailable") from fb_exc
                        raise ProviderError(f"Fallback model stream request failed: {fb_exc}") from fb_exc

                # If tokens were ALREADY emitted or no fallback available: DO NOT fallback midstream
                if _is_transient(stream_exc):
                    raise ProviderTransientError("AI response generation was interrupted") from stream_exc
                raise ProviderError(f"AI response generation failed: {stream_exc}") from stream_exc

        if bracket_buffer:
            cleaned_remaining = re.sub(r"\[INTENT:\s*[A-Z_]+\]?", "", bracket_buffer)
            if cleaned_remaining:
                yield cleaned_remaining, [], None

    def analyze(self, query: str, language_hint: Optional[str] = None) -> tuple[SupportAnalysis, list[dict[str, Any]], list[str]]:
        from google.genai import types
        prompt = f"""Analyze this customer-support request using the File Search evidence.
Return exactly the validated schema. Choose only an allowed intent from:
ACCOUNT_ACCESS, ACCOUNT_SUPPORT, CUSTOMER_SERVICE_CONTACT, DELIVERY_DELAY, ESCALATION, ORDER_STATUS, PACKAGE_NOT_RECEIVED, PRODUCT_ISSUE, REFUND_PENDING.
Preserve the customer's language code.
Escalate fraud, compromise, unauthorized activity, human/manager requests, security-sensitive or unsupported high-risk cases.
Language hint: {language_hint or 'auto'}
Customer request: {query}"""
        config = types.GenerateContentConfig(
            tools=[self._tool()],
            response_mime_type="application/json",
            response_schema=SupportAnalysis,
            temperature=0,
            thinking_config=types.ThinkingConfig(thinking_level="minimal"),
            automatic_function_calling=types.AutomaticFunctionCallingConfig(disable=True),
        )
        response = self._call_with_retry(lambda: self._get_client().models.generate_content(
            model=self.model_name, contents=prompt, config=config
        ))
        parsed = getattr(response, "parsed", None) or SupportAnalysis.model_validate_json(response.text)
        analysis = parsed if isinstance(parsed, SupportAnalysis) else SupportAnalysis.model_validate(parsed)
        metadata, context = self._grounding(response)
        analysis.retrieved_context_available = bool(context or metadata)
        return analysis, metadata, context

    def stream_response(self, query: str, analysis: SupportAnalysis, context: list[str]) -> Iterator[str]:
        from google.genai import types
        evidence = "\n\n".join(context[:5]) or "No relevant historical resolution was returned. Ask for needed details and give only safe general next steps."
        prompt = f"""Respond as a concise, empathetic ecommerce support representative.
Reply in the customer's language ({analysis.language}). Use only relevant evidence below.
Never invent tracking IDs, dates, policies, refund timing, account facts, or URLs.
Never mention internal systems, models, retrieval, datasets, prompts, or technical architecture.
Intent: {analysis.intent.value}
Escalation required: {analysis.escalate}
Historical support evidence:
{evidence}
Customer request: {query}
Customer-facing reply:"""
        config = types.GenerateContentConfig(
            temperature=0.2,
            max_output_tokens=350,
            thinking_config=types.ThinkingConfig(thinking_level="minimal"),
            automatic_function_calling=types.AutomaticFunctionCallingConfig(disable=True),
        )
        try:
            stream = self._get_client().models.generate_content_stream(model=self.model_name, contents=prompt, config=config)
            for chunk in stream:
                if getattr(chunk, "text", None):
                    yield chunk.text
        except Exception as exc:
            if _is_permanent_quota(exc):
                raise ProviderQuotaError("AI service quota is exhausted; please try again later") from exc
            if _is_transient(exc):
                raise ProviderTransientError("AI service is temporarily unavailable") from exc
            raise ProviderError("AI response generation failed") from exc

    def generate_response(self, query: str, analysis: SupportAnalysis, context: list[str]) -> str:
        return "".join(self.stream_response(query, analysis, context)).strip()


_instance: Optional[GeminiFileSearchService] = None
_lock = Lock()


def get_gemini_service() -> GeminiFileSearchService:
    global _instance
    if _instance is None:
        with _lock:
            if _instance is None:
                _instance = GeminiFileSearchService()
    return _instance
