"""
Response Safety and Information Leakage Validator.
Scans generated LLM text to ensure:
1. Response is non-empty and well-formed.
2. No internal technical system or architecture terms leak into customer responses
   (e.g., Pinecone, vector database, dataset, training data, AI model, system prompt, Gemini).
3. No meta-prompt artifacts or refusal loops.
"""

import re
from typing import Optional, Tuple

# Banned internal technical tokens (case-insensitive)
BANNED_LEAKAGE_PATTERNS = [
    re.compile(r"\bpinecone\b", re.IGNORECASE),
    re.compile(r"\bvector\s+database\b", re.IGNORECASE),
    re.compile(r"\bvector\s+store\b", re.IGNORECASE),
    re.compile(r"\btraining\s+data\b", re.IGNORECASE),
    re.compile(r"\bdataset\b", re.IGNORECASE),
    re.compile(r"\bai\s+model\b", re.IGNORECASE),
    re.compile(r"\blanguage\s+model\b", re.IGNORECASE),
    re.compile(r"\bllm\b", re.IGNORECASE),
    re.compile(r"\bgemini\b", re.IGNORECASE),
    re.compile(r"\bsystem\s+prompt\b", re.IGNORECASE),
    re.compile(r"\bcluster_id\b", re.IGNORECASE),
    re.compile(r"\bas\s+an\s+ai\b", re.IGNORECASE),
    re.compile(r"\bi\s+am\s+an\s+ai\b", re.IGNORECASE),
    re.compile(r"\bbased\s+on\s+the\s+historical\s+(cases|examples|resolutions)\b", re.IGNORECASE),
    re.compile(r"\baccording\s+to\s+my\s+(database|system|prompt)\b", re.IGNORECASE),
]


class ResponseValidationResult:
    """Encapsulates validation outcome and audit reason."""
    def __init__(self, is_valid: bool, sanitized_text: str, reason: Optional[str] = None):
        self.is_valid = is_valid
        self.sanitized_text = sanitized_text
        self.reason = reason

    def to_dict(self):
        return {
            "is_valid": self.is_valid,
            "sanitized_text": self.sanitized_text,
            "reason": self.reason
        }


def validate_response(raw_text: str) -> ResponseValidationResult:
    """
    Validates and sanitizes the response text generated by Gemini.

    Args:
        raw_text: The direct output text from the LLM.

    Returns:
        ResponseValidationResult with validity flag, cleaned text, and violation explanation.
    """
    if not raw_text or not raw_text.strip():
        return ResponseValidationResult(
            is_valid=False,
            sanitized_text="",
            reason="Empty or whitespace-only response generated."
        )

    cleaned = raw_text.strip()

    # Remove any unwanted leading 'Customer Response:' or markdown quote blocks if generated
    cleaned = re.sub(r"^(CUSTOMER RESPONSE:\s*)+", "", cleaned, flags=re.IGNORECASE).strip()

    # Scan for forbidden leakage terms
    for pattern in BANNED_LEAKAGE_PATTERNS:
        match = pattern.search(cleaned)
        if match:
            violating_phrase = match.group(0)
            return ResponseValidationResult(
                is_valid=False,
                sanitized_text="",
                reason=f"Information leakage detected: contains forbidden term '{violating_phrase}'."
            )

    # Sanity check minimum length (avoid single-word non-answers)
    if len(cleaned.split()) < 3:
        return ResponseValidationResult(
            is_valid=False,
            sanitized_text=cleaned,
            reason="Response too short to constitute a complete resolution."
        )

    return ResponseValidationResult(
        is_valid=True,
        sanitized_text=cleaned,
        reason=None
    )
