name = "hiver-ai-support-proxy"
main = "worker.js"
compatibility_date = "2024-03-01"

[vars]
BACKEND_API_URL = "https://hiver-assignment-yd38.onrender.com"
TURNSTILE_ENABLED = "false"
ALLOWED_ORIGINS = "https://hiver-ankur.vercel.app,http://localhost:3000"

[[d1_databases]]
binding = "DB"
database_name = "hiver-conversations"
database_id = "881bd03e-5cb4-47a7-b752-339fa3ce2a46"
migrations_dir = "migrations"